### ISSUE TITLE
App crashes when CCLocalLevels contains an empty level

### ISSUE THREAD

**Issue by hawkyre** [SMJSGaming/GD-API#4]
When going to the /api/save/level/json/ path, if the submitted CCLocalLevels.dat file contains a newly created level the app crashes.

Log: 
```
Error case #1
Time of error: 1584554684215
Section: level-save-select
TypeError: Cannot read property 'startsWith' of undefined
    at EncodedLevelSaveParametersToJson.k4 (C:\Users\XGen26\dev\gd\GD-NodeJS-API-master\api\converters\save\EncodedLevelSaveParametersToJson.js:66:22)
    at EncodedLevelSaveParametersToJson.converter (C:\Users\XGen26\dev\gd\GD-NodeJS-API-master\api\converters\save\EncodedLevelSaveParametersToJson.js:53:51)
    at SelectiveLevelSaveService.service (C:\Users\XGen26\dev\gd\GD-NodeJS-API-master\api\services\save\SelectiveLevelSaveService.js:46:51)
    at C:\Users\XGen26\dev\gd\GD-NodeJS-API-master\api\controllers\LevelSaveController.js:100:75
    at Array.forEach (<anonymous>)
    at C:\Users\XGen26\dev\gd\GD-NodeJS-API-master\api\controllers\LevelSaveController.js:99:30
    at Layer.handle [as handle_request] (C:\Users\XGen26\dev\gd\GD-NodeJS-API-master\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\XGen26\dev\gd\GD-NodeJS-API-master\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\XGen26\dev\gd\GD-NodeJS-API-master\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\XGen26\dev\gd\GD-NodeJS-API-master\node_modules\express\lib\router\layer.js:95:5)

<--- Last few GCs --->

[27532:000002127841BB60]    59630 ms: Mark-sweep 2056.9 (2078.9) -> 2055.0 (2083.1) MB, 788.1 / 0.0 ms  (average mu = 0.075, 
current mu = 0.041) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 00007FF6A521463D]
Security context: 0x00a8d17408a1 <JSObject>
    1: jsonPush [000000B2044798C1] [C:\Users\XGen26\dev\gd\GD-NodeJS-API-master\api\converters\level\LevelDataToJson.js:~133] [pc=0000019AD7482422](this=0x00b204478619 <LevelDataToJson map = 00000027CF80F1B1>,0x02e1779c8e69 <JSArray[49267]>,0x02e1779c8e89 <JSArray[73159]>,0,0x0199a25c06e1 <false>,0x0199a25c04a9 <undefined>)
    2: objects [000000B204479851...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF6A464232F napi_wrap+124543
 2: 00007FF6A45E36A6 v8::base::CPU::has_sse+34502
 3: 00007FF6A45E4366 v8::base::CPU::has_sse+37766
 4: 00007FF6A4DE8C5E v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF6A4DD0CA1 v8::SharedArrayBuffer::Externalize+833
 6: 00007FF6A4C9E56C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1436
 7: 00007FF6A4CA9910 v8::internal::Heap::ProtectUnprotectedMemoryChunks+1312
 8: 00007FF6A4CA6444 v8::internal::Heap::PageFlagsAreConsistent+3204
 9: 00007FF6A4C9BCD3 v8::internal::Heap::CollectGarbage+1283
10: 00007FF6A4C9A4A4 v8::internal::Heap::AddRetainedMap+2356
11: 00007FF6A4CB45AE v8::internal::Factory::AllocateRawFixedArray+94
12: 00007FF6A4CBB944 v8::internal::Factory::NewFixedArrayWithFiller+52
13: 00007FF6A4CBB901 v8::internal::Factory::NewUninitializedFixedArray+65
14: 00007FF6A4B8C4DF v8::internal::FeedbackNexus::ic_state+56319
15: 00007FF6A4B9E155 v8::Object::GetIsolate+13461
16: 00007FF6A4B85BFD v8::internal::FeedbackNexus::ic_state+29469
17: 00007FF6A4B425C7 v8::internal::JSObject::AddDataElement+999
18: 00007FF6A4B003CF v8::internal::PrototypeUsers::Add+1983
19: 00007FF6A4B1B58D v8::internal::Object::SetProperty+237
20: 00007FF6A4A148AF v8::internal::Runtime::SetObjectProperty+303
21: 00007FF6A4A13DC5 v8::internal::Runtime::GetObjectProperty+17637
22: 00007FF6A521463D v8::internal::SetupIsolateDelegate::SetupHeap+567949
23: 0000019AD7482422
```

**Comment by SMJSProductions** [comment]
This is indeed a bug since I didn't know before that new levels do not contain k4 meaning that `/api/converters/save/EncodedLevelSaveParametersToJson.js` fails. I will fix this later on

sprint item:
* story points: 0.1
* reason: it's a single condition I need to add to make sure k4 exists

**Comment by SMJSProductions** [comment]
Fixed the bug in the master branch
